apiVersion: v1
kind: PersistentVolume
metadata: 
  name: pv-stateful
  labels:
    my-vol: ps-pv
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual-storage
  capacity:
    storage: 50Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /hello