apiVersion: v1
kind: Service
metadata:
  name: nginx-headless-service
  labels:
    statefulset: nginx
spec:
  ports:
    - port: 80

  clusterIP: None
  selector:
    statefulset: nginx

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stateful-nginx
  labels:
    statefulset: nginx
spec:
  serviceName: nginx-headless-service
  replicas: 2
  #podManagementPolicy: Parallel
  # default: Ordered.

  selector:
    matchLabels:
      statefulset: nginx

  template:
    metadata:
      labels:
        statefulset: nginx
    spec:
      containers:
        - name: my-container
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: volume-name
              mountPath: /usr/share/nginx/html

  # volumes:
  #   - name: host-volume
  #     persistentVolumeClaim:
  #       claimName: host-pvc

  volumeClaimTemplates:
    - metadata:
        name: volume-name
      spec:
        storageClassName: standard

        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Mi

