apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-pv

spec:
  capacity:
    storage: 10Gi
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /kube-storage