apiVersion: v1
kind: Pod
metadata:
  name: hostpath-volume
spec:
  containers:
    - image: redis
      name: redis-container
      volumeMounts:
        - mountPath: /test-mnt
          name: test-vol


  volumes:
    - name: test-vol
      hostPath:
        path: /test-vol



#mountPath: path inside a pod
#path in hostPath: Volume(on node)