apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
    - name: ed-pod
      image: redis
      volumeMounts:
        - name: cache-volume
          mountPath: /cache
  volumes:
    - name: cache-volume
      emptyDir: {}