apiVersion: v1
kind: Pod
metadata:
  name: hostpath-volume
spec:
  containers:
    - image: redis
      name: redis-container
      volumeMounts:
        - mountPath: /pod-volume
          name: node-volume

  volumes:
    - name: node-volume
      hostPath:
        path: /node-volume
        #type: Directory  #- optional


#mountPath: path inside a pod
#path in hostPath: Volume(on node)