apiVersion: v1
kind: PersistentVolume
metadata: 
  name: ps-pv
  labels:
    pv: vol1

spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy : Retain
#  storageClassName: mystorage
  hostPath:
    path: /hello-pv



