apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-daemonset
  labels:
    daemonset: nginx
spec:
  selector:
    matchExpressions:
      - key: daemonset
        operator: In
        values:
          - nginx
  template:
    metadata:
      labels:
        daemonset: nginx
    spec:
      containers:
      - name: nginx-container
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
          - name: ds-volume
            mountPath: /usr/share/nginx/html 

      volumes:
        - name: ds-volume
          persistentVolumeClaim:
            claimName: deploy-pvc
