apiVersion: v1
kind: PersistentVolume
metadata: 
  name: ps-pv
  labels:
    my-vol: ps-pv
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ps-fast
  capacity:
    storage: 50Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /hello