apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: pv-pvc-confusion
  labels:
    my-vol-claim: ps-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ps-fast
  resources:
    requests:
      storage: 20Gi